const INPUT_FILES = [
  './src/components/atoms/Accordion/index.ts',
  './src/components/atoms/AnimateHeight/index.js',
  './src/components/atoms/Button/index.ts',
  './src/components/atoms/CheckBox/index.ts',
  './src/components/atoms/Chip/index.ts',
  './src/components/atoms/DateSelector/index.ts',
  './src/components/atoms/DropDown/index.ts',
  './src/components/atoms/GoBack/index.ts',
  './src/components/atoms/Image/index.ts',
  './src/components/atoms/InformationBoard/index.ts',
  './src/components/atoms/LaserBeam/index.ts',
  './src/components/atoms/Loader/index.ts',
  './src/components/atoms/Popover/index.ts',
  './src/components/atoms/Popup/index.ts',
  './src/components/atoms/ProgressBar/index.ts',
  './src/components/atoms/RadioButton/index.ts',
  './src/components/atoms/ScrollTop/index.ts',
  './src/components/atoms/Select/index.ts',
  './src/components/atoms/Slider/index.ts',
  './src/components/atoms/Table/index.ts',
  './src/components/atoms/Tabs/index.ts',
  './src/components/atoms/Tag/index.ts',
  './src/components/atoms/TextArea/index.ts',
  './src/components/atoms/Ticker/index.ts',
  './src/components/atoms/ToggleSwitch/index.ts',
  // './src/components/molecules/ToggleSwitch/index.ts',
  './src/components/molecules/CheckBoxGroup/index.ts',
  './src/components/molecules/RadioButtonGroup/index.ts'
];

export default INPUT_FILES;
